string=input("Enter a string : ")
c=len(string)
a=string.count("a")
e=string.index("e")
s=string.replace("Ba","Ta")
print("Length of string is ",c)
print("First occurence of e : ",e)
print("No of a's : ",a)
print("New String : ",s)